"""add missing org_id and timestamps

Revision ID: 36c2690101e8
Revises: 7f9b2237040c
Create Date: 2026-02-27 11:24:12.404065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c2690101e8'
down_revision: Union[str, None] = '7f9b2237040c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_stock', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('payment_webhook_logs', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('pipeline_stages', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_pipeline_stages_organization_id'), 'pipeline_stages', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'pipeline_stages', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('task_comments', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_task_comments_organization_id'), 'task_comments', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'task_comments', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_comments', type_='foreignkey')
    op.drop_index(op.f('ix_task_comments_organization_id'), table_name='task_comments')
    op.drop_column('task_comments', 'organization_id')
    op.drop_constraint(None, 'pipeline_stages', type_='foreignkey')
    op.drop_index(op.f('ix_pipeline_stages_organization_id'), table_name='pipeline_stages')
    op.drop_column('pipeline_stages', 'organization_id')
    op.drop_column('payment_webhook_logs', 'created_at')
    op.drop_column('inventory_stock', 'created_at')
    # ### end Alembic commands ###
