"""make subscription contract_id nullable

Revision ID: b48584ef1dcc
Revises: 36c2690101e8
Create Date: 2026-02-27 13:58:22.137457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48584ef1dcc'
down_revision: Union[str, None] = '36c2690101e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'contract_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('subscriptions_contract_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'contracts', ['contract_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key('subscriptions_contract_id_fkey', 'subscriptions', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.alter_column('subscriptions', 'contract_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
